config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :measurements do
    get :top_ten, on: :collection
  end

  get '/startups/new' => 'startups#new'
  post '/startups' => 'startups#create'
  get '/startups' => 'startups#index'

  get '/measurements_drilldown' => 'measurements_drilldown#index'
  get '/measurements_drilldown/excel_export' => 'measurements_drilldown#excel_export'
  get '/measurements_drilldown/html_export' => 'measurements_drilldown#html_export'

  root to: 'measurements#index'
end

app/models/measurement.rb
# frozen_string_literal: true

class Measurement < ApplicationRecord
end

app/controllers/measurements_controller.rb
# frozen_string_literal: true

class MeasurementsController < ApplicationController
  def index
    query = Measurement.order('created_at DESC').limit(100)
    query = query.offset(params[:page].to_i * 100) if params[:page]
    @measurements = query.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @measurements }
    end
  end

  def show
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render xml: @measurement }
    end
  end

  def new
    @measurement = Measurement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render xml: @measurement }
    end
  end

  def edit
    @measurement = Measurement.find(params[:id])
  end

  def create
    if Measurement.where(measurement_params).exists?
      redirect_to action: :index
      return
    end

    @measurement = Measurement.new(measurement_params)
    respond_to do |format|
      if @measurement.save
        format.html { redirect_to(@measurement, notice: I18n.t('measurement_created')) }
        format.xml { render xml: @measurement, status: :created, location: @measurement }
      else
        format.html { render action: :new }
        format.xml { render xml: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to(@measurement, notice: I18n.t('measurement_updated')) }
        format.xml { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml { render xml: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @measurement = Measurement.find(params[:id])
    @measurement.destroy

    respond_to do |format|
      format.html { redirect_to(measurements_url) }
      format.xml { head :ok }
    end
  end

  def top_ten
    measurements_by_test = Measurement.all.group_by(&:test)
    unsorted_benchmarks = measurements_by_test.map do |test, measurements_for_test|
      measurements_by_params = measurements_for_test.group_by do |s|
        [s.manufacturer, s.model, s.android_version, s.ruboto_app_version, s.ruboto_platform_version, s.package_version]
      end
      unsorted_rows = measurements_by_params.map do |params, measurements_for_params|
        {
          median: measurements_for_params.sort_by(&:duration)[(measurements_for_params.size / 4).to_i].duration,
          params:,
          count: measurements_for_params.size
        }
      end
      rows = unsorted_rows.sort_by { |r| r[:median] }
      { name: test, rows:, count: measurements_for_test.size }
    end
    @benchmarks = unsorted_benchmarks.sort_by { |r| [-r[:count], -r[:rows].size] }
  end

  private

  def measurement_params
    params.require(:measurement).permit(:compile_mode, :duration, :package,
                                        :package_version, :manufacturer, :model, :android_version,
                                        :ruboto_platform_version, :ruboto_app_version, :test, :ruby_version)
  end
end

app/views/measurements/_form.html.erb
<%= bootstrap_form_for(@measurement, authenticity_token: false) do |f| %>
    <div><input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" /></div>

    <% if @measurement.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this startup from being saved:</h2>

          <ul>
            <% @measurement.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.text_field :test %>
        <%= f.text_field :duration %>
        <%= f.text_field :manufacturer %>
        <%= f.text_field :model %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :android_version %>
        <%= f.text_field :ruboto_platform_version %>
        <%= f.text_field :ruboto_app_version %>
        <%= f.text_field :package %>
        <%= f.text_field :package_version %>
      </div>
    </div>

    <div class="btn-toolbar pull-xs-right">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing startup</h1>

<%= render 'form' %>

<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>

app/views/measurements/index.html.slim
h1 Listing all measurement records

table.table.table-striped.table-sm
  tr
    th Time
    /th Package
    th align="center" Benchmark version
    th Test
    th align="center" Time ms
    th Manufacturer
    th Model
    th align="center" Android<br/>version
    th align="center" JRuby version
    th align="center" Ruboto version
    /th align="center" Compile<br/>mode
    /th align="center" Ruby<br/>version

  - @measurements.each do |measurement|
    - if measurement.created_at.to_date != @previous_date
      - @previous_date = measurement.created_at.to_date
      tr
        td class="date" colspan="2" nowrap="true" = measurement.created_at.strftime '%Y-%m-%d'

    tr
      td nowrap="true" = measurement.created_at.strftime '%H:%M'
      /td = measurement.package
      td align="center" = measurement.package_version
      td nowrap="nowrap" = measurement.test
      td align="right" style="font-weight: bold;" = measurement.duration
      td = measurement.manufacturer
      td = measurement.model
      td align="center" = measurement.android_version
      td align="center" = measurement.ruboto_platform_version
      td align="center" = measurement.ruboto_app_version
      /td align="center" = measurement.compile_mode
      /td align="center" = measurement.ruby_version

app/views/measurements/new.html.slim
h1 New measurement

= render 'form'

= link_to 'Back', startups_path

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Package:</b>
  <%= @measurement.package %>
</p>

<p>
  <b>Package version:</b>
  <%= @measurement.package_version %>
</p>

<p>
  <b>Duration:</b>
  <%= @measurement.duration %> ms
</p>

<p>
  <b>Manufacturer:</b>
  <%= @measurement.manufacturer %>
</p>

<p>
  <b>Model:</b>
  <%= @measurement.model %>
</p>

<p>
  <b>Android version:</b>
  <%= @measurement.android_version %>
</p>

<p>
  <b>Ruboto platform version:</b>
  <%= @measurement.ruboto_platform_version %>
</p>

<p>
  <b>Ruboto app version:</b>
  <%= @measurement.ruboto_app_version %>
</p>


<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/top_ten.html.slim
h1 Top ten results by category

- @benchmarks.each do |benchmark|
  h3 Top #{benchmark[:name]} (#{benchmark[:count]} measurements, #{benchmark[:rows].size} variants)

  table.table.table-sm.table-striped
    tr
      th Rank
      th Time
      th Manufacturer
      th Model
      th Android
      th Ruboto
      th JRuby version
      /th Benchmark App
      th Benchmark version
      /th Compile mode
      /th Ruby version

    - benchmark[:rows].each_with_index do |r, j|
      tr
        td align="right" = j + 1
        td align="right" style="font-weight: bold;" = r[:median]
        - r[:params].each_with_index do |f, i|
          td align="#{[0].include? i ? 'right' : 'left'}" = f