config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :measurements do
    get :top_ten, on: :collection
  end

  get '/startups/new' => 'startups#new'
  post '/startups' => 'startups#create'
  get '/startups' => 'startups#index'

  get '/measurements_drilldown' => 'measurements_drilldown#index'
  get '/measurements_drilldown/excel_export' => 'measurements_drilldown#excel_export'
  get '/measurements_drilldown/html_export' => 'measurements_drilldown#html_export'

  root to: 'measurements#index'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title DOMO ARIGATO Ruboto Benchmarks Server
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta http-equiv="x-ua-compatible" content="ie=edge"
    meta name="timestamp" content="<%= Time.now.iso8601 %>"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav.navbar.navbar-light.bg-faded role="navigation"
      a.navbar-brand href="/"
        img#brand_logo src=image_path('ruboto_logo.png')
      h1#ruboto__ruby_on_android.navbar-brand Ruboto Benchmarks
      ul.nav.navbar-nav
        li.nav-item
          = link_to 'Top ten', top_ten_measurements_path, class: 'nav-link'
        li.nav-item
          = link_to 'All', measurements_path, class: 'nav-link'

      ul.nav.navbar-nav.pull-xs-right.col-md-6
        li.nav-item
          p
            ' Ruboto allows you to run Ruby scripts and develop full native
            ' stand-alone apps on Android devices. Using Ruby code, you have
            ' access to the complete Android API.
            ' For more information please visit the
            a> href='http://ruboto.org/' Ruboto
            ' home page.

    .container-fluid
      = yield